export const products = [
  {
    id: 1,
    productName: 'Nike Sneakers',
    productDesc: 'Beautiful Nike Sneakers for you!',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/nike-sneakers.png',
    size: [41, 42, 43, 44, 45, 46],
    price: 200,
    salePrice: 0,
    category: 'shoes',
    collection: ['on-sale', 'new', 'autmn-winter-2022'],
  },
  {
    id: 5,
    productName: 'Nike Sneakers Air Force',
    productDesc: 'Beautiful Air Force Nike Sneakers for you!',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/nike-sneakers-yellow.jpg',
    size: [41, 42, 43, 44, 45, 46],
    price: 300,
    salePrice: 199,
    category: 'shoes',
    collection: ['on-sale', 'new', 'autmn-winter-2022'],
  },
  {
    id: 2,
    productName: 'Adidas Sneakers',
    productDesc: 'Beautiful Adidas Sneakers for you!',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/adidas-sneakers.jpg',
    size: [41, 42, 43, 44, 45, 46],
    price: 300,
    salePrice: 249,
    category: 'shoes',
    collection: ['on-sale', 'new', 'autmn-winter-2022'],
  },
  {
    id: 3,
    productName: 'Create Purpose T-Shirt',
    productDesc: 'Beautiful T-Shirt for you!',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/blue-shirt-m.jpg',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    price: 200,
    salePrice: 0,
    category: 'clothing',
    collection: ['on-sale'],
  },
  {
    id: 4,
    productName: 'Plain white T-Shirt',
    productDesc: 'Beautiful plain white T-Shirt for you!',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/white-shirt-m.jpg',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    price: 300,
    salePrice: 199,
    category: 'clothing',
    collection: ['on-sale', 'new'],
  },
  {
    id: 6,
    productName: 'Support your local T-Shirt',
    productDesc: 'Beautiful Support your local T-Shirt',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/white-shirt-f.jpg',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    price: 300,
    salePrice: 199,
    category: 'clothing',
    collection: ['on-sale'],
  },
  {
    id: 7,
    productName: 'Adidas sneakers grey-black',
    productDesc: 'Beautiful Adidas sneakers for you!',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/adidas-sneakers-grey.jpg',
    size: [39, 40, 41, 42, 43, 44, 45],
    price: 300,
    salePrice: 199,
    category: 'shoes',
    collection: ['on-sale', 'new', 'autmn-winter-2022'],
  },
  {
    id: 8,
    productName: 'Adidas Snekaers red-white',
    productDesc: 'Beautiful Adidas red-white sneakers',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/adidas-sneakers-white-red.jpg',
    size: [39, 40, 41, 42, 43, 44, 45],
    price: 300,
    salePrice: 199,
    category: 'shoes',
    collection: ['on-sale'],
  },
  {
    id: 9,
    productName: 'Save Me T-Shirt',
    productDesc: 'Black Save me T-shirt!',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/black-shirt-m.jpg',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    price: 300,
    salePrice: 199,
    category: 'clothing',
    collection: ['on-sale', 'new'],
  },
  {
    id: 10,
    productName: 'Peace T-Shirt for men',
    productDesc: 'Peace sign skeleton hand T-shirt for men',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/black-white-shirt-m.jpg',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    price: 300,
    salePrice: 199,
    category: 'clothing',
    collection: ['on-sale'],
  },
  {
    id: 11,
    productName: 'Khaki T-Shirt',
    productDesc: 'Beautiful Khaki T-Shirt',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/brown-shirt-m.jpg',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    price: 300,
    salePrice: 199,
    category: 'clothing',
    collection: ['on-sale'],
  },
  {
    id: 12,
    productName: 'Nike custom sneakers',
    productDesc: 'Green-yellow Nike custom sneakers',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/nike-sneakers-green.jpg',
    size: [39, 40, 41, 42, 43, 44, 45],
    price: 300,
    salePrice: 199,
    category: 'shoes',
    collection: ['autmn-winter-2022'],
  },
  {
    id: 13,
    productName: 'Nike red sneakers',
    productDesc: 'Red-white Nike sneakers',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/nike-sneakers-orange.jpg',
    size: [39, 40, 41, 42, 43, 44, 45],
    price: 300,
    salePrice: 199,
    category: 'shoes',
    collection: ['on-sale', 'autmn-winter-2022'],
  },
  {
    id: 14,
    productName: 'Puma sneakers',
    productDesc: 'Classic white Puma sneakers',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/puma-snekaers-white.jpg',
    size: [39, 40, 41, 42, 43, 44, 45],
    price: 300,
    salePrice: 199,
    category: 'shoes',
    collection: ['on-sale'],
  },
  {
    id: 15,
    productName: 'Smiley face T-Shirt',
    productDesc: 'Cool smiley face T-shirt',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/white-red-shirt-f.jpg',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    price: 300,
    salePrice: 199,
    category: 'clothing',
    collection: ['on-sale'],
  },
  {
    id: 16,
    productName: 'Peace T-Shirt for women',
    productDesc: 'Peace sign skeleton hand T-shirt for women',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/black-white-shirt-f.jpg',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    price: 300,
    salePrice: 199,
    category: 'clothing',
    collection: ['on-sale'],
  },
];

export const categories = [
  {
    catId: 'shoes',
    catName: 'Shoes',
    catImg: 'images/slides/shoes-category.jpg',
  },
  {
    catId: 'clothing',
    catName: 'Clothing',
    catImg: 'images/slides/clothing-category.jpg',
  },
  {
    catId: 'accessories',
    catName: 'Accesories',
    catImg: 'images/slides/accessories-category.jpg',
  },
];
export const collections = [
  {
    colId: 'autmn-winter-2022',
    colName: 'Autmn/Winter 2022',
    colImg: 'images/slides/slide1.png',
  },
  {
    colId: 'new',
    colName: 'New',
    colImg: 'images/slides/slide2.png',
  },
  {
    colId: 'on-sale',
    colName: 'ON SALE',
    colImg: 'images/slides/slide3.png',
  },
  {
    colId: 'best-sellers',
    colName: 'Best sellers',
    colImg: 'images/slides/slide4.jpg',
  },
];
