export const products = [
  {
    id: 1,
    productName: 'Nike Sneakers',
    productDesc: 'Beautiful Nike Sneakers for you!',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/nike-sneakers.png',
    size: [41, 42, 43, 44, 45, 46],
    price: 200,
    salePrice: 99,
    category: 'Shoes',
    collection: null,
  },
  {
    id: 5,
    productName: 'Nike Sneakers Air Force',
    productDesc: 'Beautiful Air Force Nike Sneakers for you!',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/nike-sneakers-yellow.jpg',
    size: [41, 42, 43, 44, 45, 46],
    price: 300,
    salePrice: 199,
    category: 'Shoes',
    collection: null,
  },
  {
    id: 2,
    productName: 'Adidas Sneakers',
    productDesc: 'Beautiful Adidas Sneakers for you!',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/adidas-sneakers.jpg',
    size: [41, 42, 43, 44, 45, 46],
    price: 300,
    salePrice: 249,
    category: 'Shoes',
    collection: null,
  },
  {
    id: 3,
    productName: 'Nike T-Shirt',
    productDesc: 'Beautiful Nike T-Shirt for you!',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/blue-shirt-m.jpg',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    price: 200,
    salePrice: 0,
    category: 'Clothing',
    collection: null,
  },
  {
    id: 4,
    productName: 'Adidas T-Shirt',
    productDesc: 'Beautiful Adidas T-Shirt for you!',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/white-shirt-m.jpg',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    price: 300,
    salePrice: 199,
    category: 'Clothing',
    collection: null,
  },
  {
    id: 6,
    productName: 'Adidas T-Shirt',
    productDesc: 'Beautiful Adidas T-Shirt for you!',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/white-shirt-f.jpg',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    price: 300,
    salePrice: 199,
    category: 'Clothing',
    collection: null,
  },
  {
    id: 7,
    productName: 'Adidas T-Shirt',
    productDesc: 'Beautiful Adidas T-Shirt for you!',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/adidas-sneakers-grey.jpg',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    price: 300,
    salePrice: 199,
    category: 'Clothing',
    collection: null,
  },
  {
    id: 8,
    productName: 'Adidas T-Shirt',
    productDesc: 'Beautiful Adidas T-Shirt for you!',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/adidas-sneakers-white-red.jpg',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    price: 300,
    salePrice: 199,
    category: 'Clothing',
    collection: null,
  },
  {
    id: 9,
    productName: 'Adidas T-Shirt',
    productDesc: 'Beautiful Adidas T-Shirt for you!',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/black-shirt-m.jpg',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    price: 300,
    salePrice: 199,
    category: 'Clothing',
    collection: null,
  },
  {
    id: 10,
    productName: 'Adidas T-Shirt',
    productDesc: 'Beautiful Adidas T-Shirt for you!',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/black-white-shirt-m.jpg',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    price: 300,
    salePrice: 199,
    category: 'Clothing',
    collection: null,
  },
  {
    id: 11,
    productName: 'Adidas T-Shirt',
    productDesc: 'Beautiful Adidas T-Shirt for you!',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/brown-shirt-m.jpg',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    price: 300,
    salePrice: 199,
    category: 'Clothing',
    collection: null,
  },
  {
    id: 12,
    productName: 'Adidas T-Shirt',
    productDesc: 'Beautiful Adidas T-Shirt for you!',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/nike-sneakers-green.jpg',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    price: 300,
    salePrice: 199,
    category: 'Clothing',
    collection: null,
  },
  {
    id: 13,
    productName: 'Adidas T-Shirt',
    productDesc: 'Beautiful Adidas T-Shirt for you!',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/nike-sneakers-orange.jpg',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    price: 300,
    salePrice: 199,
    category: 'Clothing',
    collection: null,
  },
  {
    id: 14,
    productName: 'Adidas T-Shirt',
    productDesc: 'Beautiful Adidas T-Shirt for you!',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/puma-snekaers-white.jpg',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    price: 300,
    salePrice: 199,
    category: 'Clothing',
    collection: null,
  },
  {
    id: 15,
    productName: 'Adidas T-Shirt',
    productDesc: 'Beautiful Adidas T-Shirt for you!',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/white-red-shirt-f.jpg',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    price: 300,
    salePrice: 199,
    category: 'Clothing',
    collection: null,
  },
  {
    id: 16,
    productName: 'Adidas T-Shirt',
    productDesc: 'Beautiful Adidas T-Shirt for you!',
    longDesc:
      '<p>Velit anim velit velit in amet ea <strong>officia dolore sunt</strong>. Duis in est eu duis est officia commodo mollit eu. <ul><li>Consectetur</li> <li>esse ex dolore</li> <li>officia</li></ul> Officia ipsum dolor anim qui consectetur. <p>Consectetur elit deserunt quis aliquip magna. Dolore veniam excepteur elit ex veniam aliquip do esse sunt ad quis culpa deserunt. Cillum quis aute id pariatur adipisicing sit nisi voluptate sint labore culpa laboris. Et deserunt consequat amet ex nisi commodo cillum aliquip tempor ea cupidatat do. Amet veniam aliqua aliqua nostrud ex laborum Lorem in laboris dolore nulla id dolor esse. Est anim aute magna consectetur tempor occaecat nulla consectetur ex voluptate fugiat non deserunt anim. Pariatur incididunt esse commodo labore adipisicing sunt ut consequat veniam nisi elit occaecat id aliquip.</p><p>Eu aliquip do eu in dolore. Enim sint velit deserunt consectetur pariatur dolor et minim laboris adipisicing occaecat id. Ipsum id ullamco nulla ea ex laborum sit laboris ex quis id ad. Nisi occaecat Lorem velit ad officia eu esse non nulla. Commodo incididunt exercitation laboris nostrud id quis dolore fugiat occaecat excepteur. Excepteur sint ad nostrud ut.</p><p>Enim est qui do ea ullamco nulla irure pariatur officia incididunt ullamco reprehenderit proident laborum. Proident nulla quis esse proident qui reprehenderit ullamco aliquip eiusmod. Sit sint veniam sint proident reprehenderit amet est incididunt qui. Aliquip laboris ad ex adipisicing ea ea irure aliquip enim.</p>',
    productImg: 'images/products/black-white-shirt-f.jpg',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    price: 300,
    salePrice: 199,
    category: 'Clothing',
    collection: null,
  },
];

export const categories = [
  {
    catId: 1,
    catName: 'Shoes',
  },
  {
    catId: 2,
    catName: 'Clothing',
  },
];
export const collections = [
  {
    colId: 1,
    colName: 'Autmn/Winter 2022',
  },
  {
    colId: 2,
    colName: 'New Collection',
  },
];
